import google.generativeai as genai
import json
import os

import uuid
from datetime import datetime
import random



def generate_realistic_notes(num_notes=1000):
    notes = []

    for _ in range(num_notes):
        
        general_topic = random.choice(["technology", "science", "art", "history", "business", "health"])
        
        
        prompt = (
            f"Please create a note on the topic of {general_topic}. "
            "The note should include:\n"
            "1. A meaningful and engaging title.\n"
            "2. A detailed content section that covers the topic in depth.\n"
            "3. A concise description summarizing the note's main points.\n"
            "The style should be informative and suitable for a general audience."
        )

        model = genai.GenerativeModel(model_name="gemini-pro-1.5")
        response = model.generate_content(prompt)

        
        note = {
            "title": response.result["title"],
            "content": response.result["content"],
            "description": response.result["description"],
            "is_public": bool(random.getrandbits(1)),
            "share_link": "Generated by Gemini-pro",
            "user_id": str(uuid.uuid4()),
            "group_ids": [],
            "tag_ids": [str(uuid.uuid4()) for _ in range(random.randint(1, 5))],
            "favorited_by_ids": [str(uuid.uuid4()) for _ in range(random.randint(0, 5))],
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
            "deleted_at": None
        }
        
        notes.append(note)

    return notes


realistic_notes = generate_realistic_notes(1000)
with open("realistic_notes.json", "w") as file:
    json.dump(realistic_notes, file, indent=4)

print("Realistic notes generated and saved to 'realistic_notes.json'.")
