import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Poppins } from "next/font/google";
import AppSidebar from "@/components/layout/sidebar";
import AppBottomBar from "@/components/layout/top-bar";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Edunote | Social Education & Note Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${poppins.className} h-full bg-background antialiased relative w-screen overflow-x-clip`}
        >
          <Toaster position="bottom-right" duration={2000} richColors />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider>
              <AppSidebar />
              <main className="relative pt-[120px] ml-[280px] h-full px-4 z-20">
                <div className="max-w-screen-xl mx-auto">{children}</div>
              </main>
              <AppBottomBar />
            </TooltipProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
